name: Check PR dependencies
on: [pull_request_target]
jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check PR Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@1ba6872857f9adb872a430d5beb027fe10344086
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
